### ISSUE TITLE
Shrink/Optimize images

### ISSUE THREAD

**Issue by robertmuehsig** [Code-Inside/Blog#11]
890MB seems... too much.

**Comment by robertmuehsig** [comment]
Tested 20 pngs on https://tinypng.com/:
![image](https://cloud.githubusercontent.com/assets/756703/3928023/6f9bc932-2403-11e4-9c50-acef78980cf7.png)

Sooo.. there is room for improvement ;)

**Comment by oliverguhr** [comment]
Hier die Software hinter Png Panda:
http://pngquant.org/

Tool der Wahl:
http://nukesaq88.github.io/Pngyu/

**Comment by oliverguhr** [comment]
pre optimized: 799 MB
optimized: 375 MB

**Comment by robertmuehsig** [comment]
:+1:

**Comment by robertmuehsig** [comment]
Awesome!
