### ISSUE TITLE
Mobile Browser Support

### ISSUE THREAD

**Issue by oliverguhr** [Code-Inside/Blog#17]
# Add support for mobile browsers.
- font is not readable
- images are to large / don't fit into the page
## Sample

![foto 01 09 14 10 40 26](https://cloud.githubusercontent.com/assets/3495355/4105998/0a18448c-31b4-11e4-90b0-9ef19dd239c5.png)

**Comment by robertmuehsig** [comment]
Images are not responsive by default in bootstrap 3. When I enhance the font size I could also check if we can set the responsive stuff to default.

Source http://stackoverflow.com/questions/17932509/images-not-responsive-by-default-in-twitter-bootstrap-3

**Comment by robertmuehsig** [comment]
Fixed with this commit https://github.com/Code-Inside/Blog/commit/e905583946e0843fb39139dffd795a0b45c19b8b
