### ISSUE TITLE
Font Issue on iPad

### ISSUE THREAD

**Issue by robertmuehsig** [Code-Inside/Blog#20]
Check Fonts on h1...h6 for iPad - primary font is Segoe UI, which will not work on iOS.

**Comment by robertmuehsig** [comment]
Idea: https://www.google.com/fonts#QuickUsePlace:quickUse/Family:Open+Sans

**Comment by robertmuehsig** [comment]
Maybe this is already done due to the design/font changes? Can you check it on your iPad @oliverguhr? Thx.

**Comment by oliverguhr** [comment]
![image](https://cloud.githubusercontent.com/assets/3495355/5445489/94991476-84b4-11e4-9c8c-7b212739187d.jpg)
Looks good to me.

**Comment by robertmuehsig** [comment]
:+1:
