### ISSUE TITLE
Header Idea

### ISSUE THREAD

**Issue by robertmuehsig** [Code-Inside/Blog#30]
Something like:
![image](https://cloud.githubusercontent.com/assets/756703/11991348/a1d2255c-aa19-11e5-8add-65b6719baf3a.png)

**Comment by robertmuehsig** [comment]
Currently:
![image](https://cloud.githubusercontent.com/assets/756703/12064978/c4095a9e-afcf-11e5-93f2-675f34177e21.png)

Idea 2:
![image](https://cloud.githubusercontent.com/assets/756703/12065020/648735c2-afd0-11e5-90e8-0b27dc4321e6.png)

**Comment by oliverguhr** [comment]
I suggest a plain white background:
![code-inside-lighter](https://cloud.githubusercontent.com/assets/3495355/12071459/7f9d842c-b0ae-11e5-8435-54ba07ac8082.PNG)

and small color bar when you scroll down the page:
![code-inside-color-bar](https://cloud.githubusercontent.com/assets/3495355/12071463/aec762c2-b0ae-11e5-97a7-539919d6a802.PNG)

**Comment by oliverguhr** [comment]
Looks good!
