### ISSUE TITLE
link not working

### ISSUE THREAD

**Issue by sanket007hzb** [Code-Inside/Blog#33]
unable to open http://blog.codeinside.eu/2015/04/17/basic-authentication-in-aspnet-webapi/

**Comment by robertmuehsig** [comment]
Thank you very much for reporting! GitHub pages moved to Jekyll 3 and they changed some routing stuff. 
See: https://github.com/jekyll/jekyll/issues/4440

I hope my fix (https://github.com/Code-Inside/Blog/commit/fa4de35ad24bc86d65419a05d7473b457b779d80) will do the trick.

**Comment by robertmuehsig** [comment]
It seems:
http://blog.codeinside.eu/2015/04/17/basic-authentication-in-aspnet-webapi/
and 
http://blog.codeinside.eu/2015/04/17/basic-authentication-in-aspnet-webapi

will work - please contact me if you found any issues.

Thanks!
